from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 501, 411))
        self.stackedWidget.setObjectName("stackedWidget")
        self.title = QtWidgets.QWidget()
        self.title.setObjectName("title")
        self.label_2 = QtWidgets.QLabel(parent=self.title)
        self.label_2.setGeometry(QtCore.QRect(340, 120, 81, 20))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(parent=self.title)
        self.label.setGeometry(QtCore.QRect(80, 60, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.chooseLogFiles_pushButton = QtWidgets.QPushButton(parent=self.title)
        self.chooseLogFiles_pushButton.setGeometry(QtCore.QRect(80, 140, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.chooseLogFiles_pushButton.setFont(font)
        self.chooseLogFiles_pushButton.setObjectName("chooseLogFiles_pushButton")
        self.prefix_groupBox = QtWidgets.QGroupBox(parent=self.title)
        self.prefix_groupBox.setGeometry(QtCore.QRect(79, 220, 341, 91))
        self.prefix_groupBox.setObjectName("prefix_groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.prefix_groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.noPrefix_radioButton = QtWidgets.QRadioButton(parent=self.prefix_groupBox)
        self.noPrefix_radioButton.setChecked(True)
        self.noPrefix_radioButton.setObjectName("noPrefix_radioButton")
        self.verticalLayout_4.addWidget(self.noPrefix_radioButton)
        self.spacedPrefix_radioButton = QtWidgets.QRadioButton(parent=self.prefix_groupBox)
        self.spacedPrefix_radioButton.setObjectName("spacedPrefix_radioButton")
        self.verticalLayout_4.addWidget(self.spacedPrefix_radioButton)
        self.stackedWidget.addWidget(self.title)
        self.parseOptions = QtWidgets.QWidget()
        self.parseOptions.setObjectName("parseOptions")
        self.start_dateTimeEdit = QtWidgets.QDateTimeEdit(parent=self.parseOptions)
        self.start_dateTimeEdit.setGeometry(QtCore.QRect(90, 60, 194, 22))
        self.start_dateTimeEdit.setDate(QtCore.QDate(2025, 1, 1))
        self.start_dateTimeEdit.setObjectName("start_dateTimeEdit")
        self.label_3 = QtWidgets.QLabel(parent=self.parseOptions)
        self.label_3.setGeometry(QtCore.QRect(70, 0, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.parseOptions)
        self.label_4.setGeometry(QtCore.QRect(30, 60, 61, 21))
        self.label_4.setObjectName("label_4")
        self.end_dateTimeEdit = QtWidgets.QDateTimeEdit(parent=self.parseOptions)
        self.end_dateTimeEdit.setGeometry(QtCore.QRect(90, 100, 194, 22))
        self.end_dateTimeEdit.setDate(QtCore.QDate(2025, 1, 1))
        self.end_dateTimeEdit.setTime(QtCore.QTime(1, 0, 0))
        self.end_dateTimeEdit.setObjectName("end_dateTimeEdit")
        self.label_5 = QtWidgets.QLabel(parent=self.parseOptions)
        self.label_5.setGeometry(QtCore.QRect(30, 100, 61, 21))
        self.label_5.setObjectName("label_5")
        self.ignoreLines_checkBox = QtWidgets.QCheckBox(parent=self.parseOptions)
        self.ignoreLines_checkBox.setGeometry(QtCore.QRect(30, 140, 171, 20))
        self.ignoreLines_checkBox.setObjectName("ignoreLines_checkBox")
        self.ignoreLineStart_lineEdit = QtWidgets.QLineEdit(parent=self.parseOptions)
        self.ignoreLineStart_lineEdit.setGeometry(QtCore.QRect(210, 140, 21, 21))
        self.ignoreLineStart_lineEdit.setObjectName("ignoreLineStart_lineEdit")
        self.label_6 = QtWidgets.QLabel(parent=self.parseOptions)
        self.label_6.setGeometry(QtCore.QRect(240, 140, 81, 21))
        self.label_6.setObjectName("label_6")
        self.ignoreLineEnd_lineEdit = QtWidgets.QLineEdit(parent=self.parseOptions)
        self.ignoreLineEnd_lineEdit.setGeometry(QtCore.QRect(330, 140, 21, 21))
        self.ignoreLineEnd_lineEdit.setObjectName("ignoreLineEnd_lineEdit")
        self.label_7 = QtWidgets.QLabel(parent=self.parseOptions)
        self.label_7.setGeometry(QtCore.QRect(370, 140, 16, 21))
        self.label_7.setObjectName("label_7")
        self.italicizeLines_checkBox = QtWidgets.QCheckBox(parent=self.parseOptions)
        self.italicizeLines_checkBox.setGeometry(QtCore.QRect(30, 170, 171, 20))
        self.italicizeLines_checkBox.setObjectName("italicizeLines_checkBox")
        self.label_8 = QtWidgets.QLabel(parent=self.parseOptions)
        self.label_8.setGeometry(QtCore.QRect(370, 170, 16, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.parseOptions)
        self.label_9.setGeometry(QtCore.QRect(240, 170, 81, 21))
        self.label_9.setObjectName("label_9")
        self.italicizeLineEnd_lineEdit = QtWidgets.QLineEdit(parent=self.parseOptions)
        self.italicizeLineEnd_lineEdit.setGeometry(QtCore.QRect(330, 170, 21, 21))
        self.italicizeLineEnd_lineEdit.setObjectName("italicizeLineEnd_lineEdit")
        self.italicizeLineStart_lineEdit = QtWidgets.QLineEdit(parent=self.parseOptions)
        self.italicizeLineStart_lineEdit.setGeometry(QtCore.QRect(210, 170, 21, 21))
        self.italicizeLineStart_lineEdit.setObjectName("italicizeLineStart_lineEdit")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.parseOptions)
        self.scrollArea.setGeometry(QtCore.QRect(29, 209, 431, 161))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 429, 159))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_10 = QtWidgets.QLabel(parent=self.parseOptions)
        self.label_10.setGeometry(QtCore.QRect(40, 190, 151, 16))
        self.label_10.setObjectName("label_10")
        self.groupBox = QtWidgets.QGroupBox(parent=self.parseOptions)
        self.groupBox.setGeometry(QtCore.QRect(299, 52, 81, 81))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.convertToHtml_checkBox = QtWidgets.QCheckBox(parent=self.groupBox)
        self.convertToHtml_checkBox.setObjectName("convertToHtml_checkBox")
        self.verticalLayout.addWidget(self.convertToHtml_checkBox)
        self.convertToPdf_checkBox = QtWidgets.QCheckBox(parent=self.groupBox)
        self.convertToPdf_checkBox.setObjectName("convertToPdf_checkBox")
        self.verticalLayout.addWidget(self.convertToPdf_checkBox)
        self.convert_pushButton = QtWidgets.QPushButton(parent=self.parseOptions)
        self.convert_pushButton.setGeometry(QtCore.QRect(380, 52, 81, 141))
        self.convert_pushButton.setObjectName("convert_pushButton")
        self.stackedWidget.addWidget(self.parseOptions)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MCLogConvert"))
        self.label_2.setText(_translate("MainWindow", "By MUGnifisent"))
        self.label.setText(_translate("MainWindow", "MCLogConvert"))
        self.chooseLogFiles_pushButton.setText(_translate("MainWindow", "-> Choose log files <-"))
        self.prefix_groupBox.setTitle(_translate("MainWindow", "Prefix"))
        self.noPrefix_radioButton.setText(_translate("MainWindow", "No prefix / no space"))
        self.spacedPrefix_radioButton.setText(_translate("MainWindow", "With space"))
        self.start_dateTimeEdit.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy HH:mm:ss"))
        self.label_3.setText(_translate("MainWindow", "Parse options"))
        self.label_4.setText(_translate("MainWindow", "Start time:"))
        self.end_dateTimeEdit.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy HH:mm:ss"))
        self.label_5.setText(_translate("MainWindow", "End time:"))
        self.ignoreLines_checkBox.setText(_translate("MainWindow", "Ignore lines, that start with:"))
        self.ignoreLineStart_lineEdit.setText(_translate("MainWindow", "("))
        self.label_6.setText(_translate("MainWindow", ", and end with:"))
        self.ignoreLineEnd_lineEdit.setText(_translate("MainWindow", ")"))
        self.label_7.setText(_translate("MainWindow", "."))
        self.italicizeLines_checkBox.setText(_translate("MainWindow", "Italicize lines, that start with:"))
        self.label_8.setText(_translate("MainWindow", "."))
        self.label_9.setText(_translate("MainWindow", ", and end with:"))
        self.italicizeLineEnd_lineEdit.setText(_translate("MainWindow", "*"))
        self.italicizeLineStart_lineEdit.setText(_translate("MainWindow", "*"))
        self.label_10.setText(_translate("MainWindow", "NICKNAME <---> COLOR"))
        self.groupBox.setTitle(_translate("MainWindow", "Convert to:"))
        self.convertToHtml_checkBox.setText(_translate("MainWindow", ".html"))
        self.convertToPdf_checkBox.setText(_translate("MainWindow", ".pdf"))
        self.convert_pushButton.setText(_translate("MainWindow", "CONVERT"))
